- hosts: all

  vars: 
   - MyMessage: "Welcome to Ansible world!"
   - DBMessage: "Hello from MongoDB"

  tasks:
   - name: NGINX | Installing NGINX repo rpm
     yum: name=http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
     become: yes
   - name: NGINX | Installing NGINX
     become: yes
     yum: name=nginx state=latest
   - name: index.html copy
     become: yes
     template: src=index.html.j2 dest=/usr/share/nginx/html/index.html
   - name: NGINX | Starting NGINX
     become: yes
     service: name=nginx state=started
